### ISSUE TITLE
Valor inválido dado por un usuario

### ISSUE THREAD

**Issue by pyjavo** [RicardoRB09/pause#2]
Een el archivo run.py tiene esta línea

[if page_number.isdigit() and int(page_number) > 0 and int(page_number) < 22:](https://github.com/RicardoRB09/pause/blob/main/run.py#L22C9-L22C85)

Si el usuario digita un valor inválido, tampoco pondría por defecto que haga una búsqueda. En cambio, mostraría un mensaje de error (es lo que siempre se suele hacer). De esta forma le enseñas al usuario que está equivocado (de lo contrario pensara que siempre funciona y su resultado es el que trae por defecto).

**Comment by RicardoRB09** [comment]
Thanks! This validation was removed and the flow of the coding prevents this kind of situations.
